#!/bin/bash
set -euo pipefail

PATTERN="$BUILDKITE_PLUGIN_SPELL_CHECKER_PATTERN"

echo "--- Checking File Spell"

Error=$(docker run --rm -ti -v $(pwd):/workdir tmaier/markdown-spellcheck:latest "**/*.md"i)

echo "Found ${ERROR} in the file"

buildkite-agent annotate "Found ${ERROR} From The Files"
