#!/bin/bash
set -euo pipefail


echo "--- Checking File Spell"

Misspell=$(docker run --rm -ti -v $(pwd):/workdir tmaier/markdown-spellcheck:latest --report "**/*.md")

echo "Found ${Misspell} in the file"

buildkite-agent annotate "Found ${Misspell} From The Files"
